"""Agregar campo firma_filename a Acta

Revision ID: 4303c54eaddb
Revises: cfcaf5dd53f5
Create Date: 2025-06-20 23:44:11.114614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4303c54eaddb'
down_revision = 'cfcaf5dd53f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('fechas_limite')
    with op.batch_alter_table('actas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('firma_filename', sa.String(length=120), nullable=True))
        batch_op.alter_column('numero_correlativo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.alter_column('nombres',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('rut',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('tipo_contrato',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.alter_column('nombre_reemplazo',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('salud',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.alter_column('plan_isapre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('afp',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('convenio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('responsable',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('fecha_contratacion',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('periodo_remunerativo',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.alter_column('cesfam',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.create_foreign_key('fk_actas_usuario_id', 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('fecha_modificacion')
        batch_op.drop_column('firma_path')
        batch_op.drop_column('fecha_envio_fisico')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('cesfam',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('cesfam',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('actas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_envio_fisico', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('firma_path', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cesfam',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('periodo_remunerativo',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.alter_column('fecha_contratacion',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('responsable',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('convenio',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('afp',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('plan_isapre',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('salud',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('nombre_reemplazo',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('tipo_contrato',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('rut',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('apellidos',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('nombres',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('numero_correlativo',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('firma_filename')
        batch_op.drop_column('usuario_id')

    op.create_table('fechas_limite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mes', sa.INTEGER(), nullable=False),
    sa.Column('anio', sa.INTEGER(), nullable=False),
    sa.Column('fecha_limite', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
