"""crear tablas

Revision ID: 4a413f37fac9
Revises: a2f58f5d3f3c
Create Date: 2025-06-15 22:45:57.131098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a413f37fac9'
down_revision = 'a2f58f5d3f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_correlativo', sa.String(length=50), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=False),
    sa.Column('rut_reemplazo', sa.String(length=20), nullable=True),
    sa.Column('nombre_reemplazo', sa.String(length=150), nullable=True),
    sa.Column('salud', sa.String(length=50), nullable=False),
    sa.Column('plan_isapre', sa.String(length=100), nullable=True),
    sa.Column('afp', sa.String(length=100), nullable=False),
    sa.Column('convenio', sa.String(length=100), nullable=False),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('cesfam', sa.String(length=150), nullable=False),
    sa.Column('fecha_contratacion', sa.Date(), nullable=False),
    sa.Column('periodo_remunerativo', sa.String(length=7), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_envio_fisico', sa.Date(), nullable=True),
    sa.Column('firma_path', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fechas_limite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contraseña', sa.String(length=200), nullable=False),
    sa.Column('cesfam', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.drop_table('acta')
    op.drop_table('usuario')
    op.drop_table('fecha_limite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fecha_limite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mes', sa.INTEGER(), nullable=False),
    sa.Column('año', sa.INTEGER(), nullable=False),
    sa.Column('fecha_limite', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('rol', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cesfam', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('acta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombres', sa.VARCHAR(length=100), nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=100), nullable=False),
    sa.Column('rut', sa.VARCHAR(length=12), nullable=False),
    sa.Column('cesfam', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_contrato', sa.VARCHAR(length=50), nullable=False),
    sa.Column('periodo_mes', sa.INTEGER(), nullable=False),
    sa.Column('periodo_año', sa.INTEGER(), nullable=False),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('fecha_modificacion', sa.DATETIME(), nullable=True),
    sa.Column('fecha_envio_fisico', sa.DATE(), nullable=True),
    sa.Column('numero_acta', sa.VARCHAR(length=20), nullable=True),
    sa.Column('firma_archivo', sa.VARCHAR(length=120), nullable=True),
    sa.Column('rut_reemplazo', sa.VARCHAR(length=12), nullable=True),
    sa.Column('nombre_reemplazo', sa.VARCHAR(length=100), nullable=True),
    sa.Column('salud', sa.VARCHAR(length=50), nullable=True),
    sa.Column('plan_isapre', sa.VARCHAR(length=100), nullable=True),
    sa.Column('afp', sa.VARCHAR(length=50), nullable=True),
    sa.Column('convenio', sa.VARCHAR(length=100), nullable=True),
    sa.Column('responsable', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usuarios')
    op.drop_table('fechas_limite')
    op.drop_table('actas')
    # ### end Alembic commands ###
