"""Inicial

Revision ID: a2f58f5d3f3c
Revises: 
Create Date: 2025-06-15 21:36:37.067668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f58f5d3f3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('cesfam', sa.String(length=100), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=False),
    sa.Column('periodo_mes', sa.Integer(), nullable=False),
    sa.Column('periodo_año', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_envio_fisico', sa.Date(), nullable=True),
    sa.Column('numero_acta', sa.String(length=20), nullable=True),
    sa.Column('firma_archivo', sa.String(length=120), nullable=True),
    sa.Column('rut_reemplazo', sa.String(length=12), nullable=True),
    sa.Column('nombre_reemplazo', sa.String(length=100), nullable=True),
    sa.Column('salud', sa.String(length=50), nullable=True),
    sa.Column('plan_isapre', sa.String(length=100), nullable=True),
    sa.Column('afp', sa.String(length=50), nullable=True),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fecha_limite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('cesfam', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('fecha_limite')
    op.drop_table('acta')
    # ### end Alembic commands ###
