"""Agregar campo username a Usuario

Revision ID: a5734e64e888
Revises: 4a413f37fac9
Create Date: 2025-06-15 23:01:09.795459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5734e64e888'
down_revision = '4a413f37fac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fechas_limite')
    op.drop_table('usuarios')
    op.drop_table('actas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('numero_correlativo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nombres', sa.VARCHAR(length=150), nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=150), nullable=False),
    sa.Column('rut', sa.VARCHAR(length=20), nullable=False),
    sa.Column('tipo_contrato', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rut_reemplazo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('nombre_reemplazo', sa.VARCHAR(length=150), nullable=True),
    sa.Column('salud', sa.VARCHAR(length=50), nullable=False),
    sa.Column('plan_isapre', sa.VARCHAR(length=100), nullable=True),
    sa.Column('afp', sa.VARCHAR(length=100), nullable=False),
    sa.Column('convenio', sa.VARCHAR(length=100), nullable=False),
    sa.Column('responsable', sa.VARCHAR(length=150), nullable=True),
    sa.Column('cesfam', sa.VARCHAR(length=150), nullable=False),
    sa.Column('fecha_contratacion', sa.DATE(), nullable=False),
    sa.Column('periodo_remunerativo', sa.VARCHAR(length=7), nullable=False),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('fecha_modificacion', sa.DATETIME(), nullable=True),
    sa.Column('fecha_envio_fisico', sa.DATE(), nullable=True),
    sa.Column('firma_path', sa.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_usuario', sa.VARCHAR(length=150), nullable=False),
    sa.Column('correo', sa.VARCHAR(length=150), nullable=False),
    sa.Column('contraseña', sa.VARCHAR(length=200), nullable=False),
    sa.Column('cesfam', sa.VARCHAR(length=150), nullable=False),
    sa.Column('rol', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('fechas_limite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mes', sa.INTEGER(), nullable=False),
    sa.Column('anio', sa.INTEGER(), nullable=False),
    sa.Column('fecha_limite', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
