"""crear tablas iniciales

Revision ID: cfcaf5dd53f5
Revises: a5734e64e888
Create Date: 2025-06-15 23:06:08.637372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcaf5dd53f5'
down_revision = 'a5734e64e888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_correlativo', sa.String(length=50), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=False),
    sa.Column('rut_reemplazo', sa.String(length=20), nullable=True),
    sa.Column('nombre_reemplazo', sa.String(length=150), nullable=True),
    sa.Column('salud', sa.String(length=50), nullable=False),
    sa.Column('plan_isapre', sa.String(length=100), nullable=True),
    sa.Column('afp', sa.String(length=100), nullable=False),
    sa.Column('convenio', sa.String(length=100), nullable=False),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('cesfam', sa.String(length=150), nullable=False),
    sa.Column('fecha_contratacion', sa.Date(), nullable=False),
    sa.Column('periodo_remunerativo', sa.String(length=7), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_envio_fisico', sa.Date(), nullable=True),
    sa.Column('firma_path', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fechas_limite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('cesfam', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('fechas_limite')
    op.drop_table('actas')
    # ### end Alembic commands ###
