"""prep firma digital (campos opcionales en Acta)

Revision ID: fe54ca291f13
Revises: 29fd537fadaa
Create Date: 2025-08-09 23:56:23.861870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe54ca291f13'
down_revision = '29fd537fadaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('firmada_en', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('firma_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('firma_cn', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('firma_serial', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('firma_p7s_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actas', schema=None) as batch_op:
        batch_op.drop_column('firma_p7s_path')
        batch_op.drop_column('firma_serial')
        batch_op.drop_column('firma_cn')
        batch_op.drop_column('firma_hash')
        batch_op.drop_column('firmada_en')
        batch_op.drop_column('firma_tipo')

    # ### end Alembic commands ###
